# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        files: ^backend/
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--ignore=E501']
        files: ^backend/
  - repo: local
    hooks:
      - id: openapi-schema-update
        name: Update OpenAPI and TypeScript schemas
        entry: ./scripts/update_frontend_schemas.sh
        language: script
        files: backend/app/(schemas\.py|api/.*\.py)
