version: '3.8'

services:
  web:
    build: ./baldin
    command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 8000
    volumes:
      - ./baldin:/usr/src/app
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test
    depends_on:
      - web-db
  web-db:
    build:
      context: ./baldin/db
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"     