version: '3.8'  # Ensure this version supports all features you use

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: xpHMVyxenH
      POSTGRES_PASSWORD: GpZODNAOLkEPucEpcqXrcDqNNLGpYJxXwhuJdcLvVMgkrHkULP
    volumes:
      - ./backend/public/db:/var/lib/postgresql/data

  web:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8004:8000

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - web
