version: "3.8"

services:
  db:
    build:
      context: ./public/db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public/db/baldin:/var/lib/postgresql/data
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env

  headless-chrome:
    restart: unless-stopped
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    volumes:
      - "/dev/shm:/dev/shm"
    environment:
      - SHM_SIZE=${CHROME_SHM_SIZE}