export type CommandPaletteCommand = {
  title: string;
  description: string;
  href: string;
  section: string;
  keywords?: string[];
};

export const commandPaletteCommands: CommandPaletteCommand[] = [
  {
    title: 'Baldin Home',
    description: 'Return to the developer-preview landing page.',
    href: '/',
    section: 'Top Level',
    keywords: ['home', 'landing', 'developer preview'],
  },
  {
    title: 'Choose Your Next Step',
    description: 'Open the docs entry point for setup, architecture, implementation, and reference work.',
    href: '/docs/',
    section: 'Docs',
    keywords: ['docs home', 'start here', 'overview'],
  },
  {
    title: 'Track Release Readiness',
    description: 'See the current release posture, remaining launch phases, and deployment constraints.',
    href: '/docs/engineering/release-roadmap',
    section: 'Engineering',
    keywords: ['release readiness', 'roadmap', 'launch'],
  },
  {
    title: 'Orient Yourself',
    description: 'Start with product scope, repo layout, and the next docs most people need first.',
    href: '/docs/getting-started/overview',
    section: 'Start Here',
    keywords: ['getting started', 'repo layout', 'introduction'],
  },
  {
    title: 'Boot The Stack',
    description: 'Bring up the local stack quickly, then jump to workflow, API access, and configuration details.',
    href: '/docs/getting-started/quickstart',
    section: 'Start Here',
    keywords: ['quickstart', 'docker compose', 'local stack'],
  },
  {
    title: 'Contribute Safely',
    description: 'Choose the right workflow, validation, and ownership rules before opening a pull request.',
    href: '/docs/getting-started/contributing',
    section: 'Start Here',
    keywords: ['contributing', 'workflow', 'validation', 'ownership'],
  },
  {
    title: 'Planned Deployment',
    description: 'Review the current deployment posture, planned topology, and what is supported today.',
    href: '/docs/getting-started/deployment-guide',
    section: 'Start Here',
    keywords: ['deployment', 'production', 'topology'],
  },
  {
    title: 'Dashboard',
    description: 'Explore the unified dashboard for action items, pipeline metrics, and activity.',
    href: '/docs/features/dashboard',
    section: 'Features',
    keywords: ['dashboard', 'metrics', 'activity'],
  },
  {
    title: 'Job Search Pipeline',
    description: 'See how Baldin tracks companies, leads, and applications across the full lifecycle.',
    href: '/docs/features/job-search-pipeline',
    section: 'Features',
    keywords: ['applications', 'companies', 'leads', 'pipeline'],
  },
  {
    title: 'Document Workspace',
    description: 'Understand versioned documents, collaboration, sharing, and application attachments.',
    href: '/docs/features/document-workspace',
    section: 'Features',
    keywords: ['documents', 'collaboration', 'attachments'],
  },
  {
    title: 'Extraction and Automation',
    description: 'Review LLM-backed extraction, orchestration pipelines, and crawler management.',
    href: '/docs/features/extraction-and-automation',
    section: 'Features',
    keywords: ['automation', 'crawler', 'extraction', 'etl'],
  },
  {
    title: 'Networking and Messaging',
    description: 'Follow profiles, peer connections, direct conversations, and activity tracking.',
    href: '/docs/features/networking',
    section: 'Features',
    keywords: ['networking', 'messaging', 'connections', 'conversations'],
  },
  {
    title: 'See System Boundaries',
    description: 'Open the service-topology and runtime-boundaries overview.',
    href: '/docs/architecture/system-overview',
    section: 'Architecture',
    keywords: ['system overview', 'topology', 'runtime'],
  },
  {
    title: 'Map The Data Model',
    description: 'Inspect how profile, search, document, automation, and networking entities fit together.',
    href: '/docs/architecture/data-model',
    section: 'Architecture',
    keywords: ['data model', 'entities', 'schema'],
  },
  {
    title: 'Browse API Routes',
    description: 'Open the route groups, access rules, and contract-boundaries guide.',
    href: '/docs/architecture/api-surface',
    section: 'Architecture',
    keywords: ['api', 'routes', 'contracts'],
  },
  {
    title: 'See Frontend Boundaries',
    description: 'Review route groups, page modules, service boundaries, and contract consumption.',
    href: '/docs/architecture/frontend-architecture',
    section: 'Architecture',
    keywords: ['frontend', 'routes', 'services', 'ui'],
  },
  {
    title: 'Trace Extraction Flows',
    description: 'Follow user-triggered extraction, persisted retries, and crawler ETL separation.',
    href: '/docs/architecture/extraction-pipeline',
    section: 'Architecture',
    keywords: ['extraction', 'pipeline', 'crawler', 'retry'],
  },
  {
    title: 'Understand Document Collaboration',
    description: 'Review versioned documents, sharing, and the Yjs bootstrap protocol.',
    href: '/docs/architecture/document-collaboration',
    section: 'Architecture',
    keywords: ['yjs', 'documents', 'collaboration'],
  },
  {
    title: 'Follow Network Flows',
    description: 'Understand directory, conversations, activity, and action-item flows.',
    href: '/docs/architecture/networking-and-messaging',
    section: 'Architecture',
    keywords: ['network', 'messaging', 'activity', 'flows'],
  },
  {
    title: 'Frontend Design System',
    description: 'Open the shipped frontend design-system architecture and compatibility rules.',
    href: '/docs/architecture/frontend-design-system',
    section: 'Design System',
    keywords: ['design system', 'theme', 'mui'],
  },
  {
    title: 'Design System Catalog',
    description: 'Inspect the canonical inventory of shipped frontend design-system surfaces.',
    href: '/docs/reference/design-system-catalog',
    section: 'Design System',
    keywords: ['catalog', 'tokens', 'primitives'],
  },
  {
    title: 'Baldin Redesign Handoff',
    description: 'Start redesign-phase work from the authoritative redesign handoff.',
    href: '/docs/reference/baldin-redesign-handoff',
    section: 'Design System',
    keywords: ['redesign', 'handoff', 'figma', 'closeout'],
  },
  {
    title: 'Redesign Implementation Program',
    description: 'Turn the redesign handoff into required briefs and route-family implementation waves.',
    href: '/docs/engineering/redesign-implementation-program',
    section: 'Design System',
    keywords: ['redesign', 'implementation', 'waves', 'briefs'],
  },
  {
    title: 'Design System Governance',
    description: 'Review the operating rules for keeping the frontend design-system layer coherent.',
    href: '/docs/engineering/design-system-governance',
    section: 'Design System',
    keywords: ['governance', 'review', 'promotion'],
  },
  {
    title: 'Design System Workflow',
    description: 'See the contribution flow, validation path, and practical handoff rules for design-system work.',
    href: '/docs/engineering/design-system-workflow',
    section: 'Design System',
    keywords: ['workflow', 'handoff', 'validation'],
  },
  {
    title: 'Design System Migration Guide',
    description: 'Review compatibility strategy, migrated surfaces, and next-step guidance.',
    href: '/docs/engineering/design-system-migration-guide',
    section: 'Design System',
    keywords: ['migration', 'adoption', 'compatibility'],
  },
  {
    title: 'Close Out Phase 2 Design System',
    description: 'Open the historical closeout for the Phase 2 design-system rollout.',
    href: '/docs/engineering/phase-2-design-system-closeout',
    section: 'Design System',
    keywords: ['phase 2', 'closeout', 'history'],
  },
  {
    title: 'Work Locally',
    description: 'Use Docker Compose first, then choose the shortest smoke-check loop that proves the change.',
    href: '/docs/engineering/local-development',
    section: 'Engineering',
    keywords: ['local development', 'docker compose', 'smoke check'],
  },
  {
    title: 'See Merge Gates',
    description: 'Review merge gates, contract freshness checks, and candidate artifact builds.',
    href: '/docs/engineering/ci-pipeline',
    section: 'Engineering',
    keywords: ['ci', 'pipeline', 'merge gates'],
  },
  {
    title: 'Regenerate API Contracts',
    description: 'Refresh OpenAPI and frontend types without drifting from the backend contract.',
    href: '/docs/engineering/contract-management',
    section: 'Engineering',
    keywords: ['openapi', 'contracts', 'schema'],
  },
  {
    title: 'Prompt The Right Agent',
    description: 'Choose the right Baldin agent surface, scope prompts cleanly, and require consistent handbacks.',
    href: '/docs/engineering/agentic-workflow-cookbook',
    section: 'Engineering',
    keywords: ['agentic workflow', 'prompts', 'agents'],
  },
  {
    title: 'Rewrite Weak Prompts',
    description: 'Turn vague prompts into scoped requests with validation and handback rules.',
    href: '/docs/engineering/agentic-prompt-examples',
    section: 'Engineering',
    keywords: ['prompt examples', 'rewrite', 'prompting'],
  },
  {
    title: 'Run The Right Checks',
    description: 'Start with the smallest effective smoke check, then widen validation only when needed.',
    href: '/docs/engineering/testing',
    section: 'Engineering',
    keywords: ['testing', 'validation', 'checks'],
  },
  {
    title: 'Open The API Docs',
    description: 'Jump to the live API docs and the route-map pages from there.',
    href: '/docs/reference/api-reference',
    section: 'Reference',
    keywords: ['api docs', 'swagger', 'routes'],
  },
  {
    title: 'Documentation Resources',
    description: 'Open the collected links to Baldin docs, API docs, admin, repo files, and related guides.',
    href: '/docs/reference/resources',
    section: 'Reference',
    keywords: ['resources', 'links', 'docs'],
  },
  {
    title: 'Look Up Settings',
    description: 'Find runtime configuration, derived startup behavior, and the settings most likely to matter.',
    href: '/docs/reference/environment-variables',
    section: 'Reference',
    keywords: ['environment', 'settings', 'config'],
  },
  {
    title: 'Decode Baldin Terms',
    description: 'Look up Baldin-specific terms that recur across architecture and engineering docs.',
    href: '/docs/reference/glossary',
    section: 'Reference',
    keywords: ['glossary', 'terms', 'definitions'],
  },
];
