name: CI
concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - ".gitmodules"
      - "*.ini"
      - "*.md"
      - "**/*.txt"
      - "docs/**"
    branches:
      - main
  pull_request:
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - ".gitmodules"
      - "*.md"
      - "**/*.txt"
      - "docs/**"
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  lint:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    env:
      PIPENV_DEFAULT_PYTHON_VERSION: ${{ matrix.python-version }}
      PYTHONWARNINGS: ignore:DEPRECATION
      PYTHONIOENCODING: "utf-8"
      GIT_ASK_YESNO: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - run: |
          python -m pip install pre-commit
          pre-commit run --all-files --verbose --show-diff-on-failure
